### ISSUE TITLE
Made the list-course a list that recive all values from theinput-course 

### ISSUE THREAD

**Issue by kasselTrankos** [srferron/lit-element-course#11]
- the list-course array at start is empty
- when the input-course has a string with minlength of 3 characteres is a able to made enter
- when is made enter the value of the input pass to the array of the list-course
- then the list-course append one by one the input-course values when click on enter

**Comment by kasselTrankos** [comment]
- The main idea is to made and append to the array of the list-course, everytime is click on enter into the inupt-course, when this has at minium of 3 characters.

**Comment by srferron** [comment]
I did that. With every click i append the value to the <h> tag, when at least 3 characters are included and the user clicks Enter, is when a new row is append to the table
